// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmLdFBU_us35K8E1ZV568FNGRvLv9zv3I',
    appId: '1:514558736408:web:61581f15b3bd2c5a4deb6d',
    messagingSenderId: '514558736408',
    projectId: 'mad-project-d0e88',
    authDomain: 'mad-project-d0e88.firebaseapp.com',
    storageBucket: 'mad-project-d0e88.firebasestorage.app',
    measurementId: 'G-7L5CVYCHM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgigZwF53UzrurbXXwtD_fyuIZH8tXtLs',
    appId: '1:514558736408:android:99679feee52402ee4deb6d',
    messagingSenderId: '514558736408',
    projectId: 'mad-project-d0e88',
    storageBucket: 'mad-project-d0e88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcZWIFDhtWgHTIBkKO5qPaWFW68ZutFW8',
    appId: '1:514558736408:ios:6fbe4e026fd1c9384deb6d',
    messagingSenderId: '514558736408',
    projectId: 'mad-project-d0e88',
    storageBucket: 'mad-project-d0e88.firebasestorage.app',
    iosBundleId: 'rathent.com.rathent01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcZWIFDhtWgHTIBkKO5qPaWFW68ZutFW8',
    appId: '1:514558736408:ios:6fbe4e026fd1c9384deb6d',
    messagingSenderId: '514558736408',
    projectId: 'mad-project-d0e88',
    storageBucket: 'mad-project-d0e88.firebasestorage.app',
    iosBundleId: 'rathent.com.rathent01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmLdFBU_us35K8E1ZV568FNGRvLv9zv3I',
    appId: '1:514558736408:web:c0dd73e69fbf915d4deb6d',
    messagingSenderId: '514558736408',
    projectId: 'mad-project-d0e88',
    authDomain: 'mad-project-d0e88.firebaseapp.com',
    storageBucket: 'mad-project-d0e88.firebasestorage.app',
    measurementId: 'G-X99Y25FE1X',
  );
}
